version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/SkyFactory_4_Server_4.1.0.zip
    ports:
      - 25565:25565
