name: Build

on:
  workflow_call:
    inputs:
      IMAGE_TO_TEST:
        required: true
        type: string
    secrets:
      IMAGE_ORG:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ inputs.IMAGE_TO_TEST }}
          load: true
          cache-from: type=gha
