name: Build and publish multiarch
on:
  push:
    branches:
      - master
      - test/**
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - java17
          - java17-openj9
          - java17-alpine
          - java8
          - java8-multiarch
          - java8-openj9
          - java11
          - java11-openj9
        include:
          - variant: java17
            baseImage: eclipse-temurin:17
            platforms: linux/amd64,linux/arm/v7,linux/arm64
            mcVersion: LATEST
          - variant: java17-openj9
            baseImage: ibm-semeru-runtimes:open-17-jdk
            platforms: linux/amd64,linux/arm64
            mcVersion: LATEST
          - variant: java17-alpine
            baseImage: eclipse-temurin:17-jdk-alpine
            platforms: linux/amd64
            mcVersion: LATEST
          - variant: java8
            baseImage: openjdk:8-jdk-alpine3.8
            platforms: linux/amd64
            mcVersion: 1.12.2
          - variant: java8-multiarch
            baseImage: eclipse-temurin:8-jdk
            platforms: linux/amd64,linux/arm64
            mcVersion: 1.12.2
          - variant: java8-openj9
            baseImage: ibm-semeru-runtimes:open-8-jdk
            platforms: linux/amd64,linux/arm64
            mcVersion: 1.12.2
          - variant: java11
            baseImage: adoptopenjdk:11-jdk-hotspot
            platforms: linux/amd64,linux/arm/v7,linux/arm64
            mcVersion: 1.16.5
          - variant: java11-openj9
            baseImage: ibm-semeru-runtimes:open-11-jdk
            platforms: linux/amd64,linux/arm64
            mcVersion: 1.16.5
    env:
      IMAGE_TO_TEST: ${{ github.repository_owner }}/minecraft-server:test-${{ matrix.variant }}-${{ github.run_id }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          # for build-files step
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # NOTE for forks: if your Docker Hub organization doesn't match your Github repo's,
          # then the use of ${{ github.repository_owner }} will need to be replaced.
          images: |
            ${{ github.repository_owner }}/minecraft-server
          tags: |
            type=ref,event=tag,enable=${{ matrix.variant == 'java17' }}
            type=ref,event=tag,suffix=-${{ matrix.variant }}
            type=raw,value=${{ matrix.variant }}
          flavor: |
            latest=${{ matrix.variant == 'java17' }}
          labels: |
            org.opencontainers.image.authors=Geoff Bourne <itzgeoff@gmail.com>

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build for test
        uses: docker/build-push-action@v2.9.0
        with:
          platforms: linux/amd64
          tags: ${{ env.IMAGE_TO_TEST }}
          # ensure latest base image is used
          pull: true
          # load into daemon for test usage in next step
          load: true
          push: false
          build-args: |
            BASE_IMAGE=${{ matrix.baseImage }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          # no cache-to to avoid cross-cache update from next build step

      - name: Run tests
        env:
          MINECRAFT_VERSION: ${{ matrix.mcVersion }}
        run: |
          tests/test.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          platforms: ${{ matrix.platforms }}
          push: ${{ github.ref_type == 'tag' || github.ref_name == 'master' }}
          tags: ${{ steps.meta.outputs.tags }}
          # ensure latest base image is used
          pull: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ matrix.baseImage }}
            BUILD_FILES_REV=${{ steps.build-files-rev.outputs.REV }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant }}
