name: ContinuousIntegration

on:
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  ci:
    runs-on: ubuntu-latest
    run-build:
      uses: ./.github/workflows/build.yml@${{ github.head_ref }}
      with:
        IMAGE_TO_TEST: ${{ env.IMAGE_TO_TEST }}
    run-test:
      uses: ./.github/workflows/test.yml@${{ github.head_ref }}
      with:
        IMAGE_TO_TEST: ${{ env.IMAGE_TO_TEST }}
    run-deploy:
      uses: ./.github/workflows/deploy.yml@${{ github.head_ref }}
      with:
        IMAGE_TO_TEST: ${{ env.IMAGE_TO_TEST }}
