name: Deploy

on:
  workflow_call:
    inputs:
      IMAGE_TO_TEST:
        required: true
        type: string

env:
  ORG: ${{ secrets.IMAGE_ORG }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Gather Docker metadata
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image') && env.ORG
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.ORG }}/minecraft-server

      - name: Login to DockerHub
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image') && env.DOCKER_USER && env.DOCKER_PASSWORD
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image') && env.ORG && env.DOCKER_USER && env.DOCKER_PASSWORD
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          push: true
          cache-from: type=gha
          labels: ${{ steps.meta.outputs.labels }}
