name: discord

on:
  workflow_run:
    workflows: ["PullRequest", "main"]
    types:
      - completed
      - requested

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  discord:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      on-success:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Github repo: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- Link: [Current Actions](<${{ env.GITHUB_WORKFLOW_URL }}>)\n- Status: 🎉  ${{ job.status }}  🍏"
      on-failure:
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Github repo: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- Link: [Current Actions](<${{ env.GITHUB_WORKFLOW_URL }}>)\n- Status: 🤔  ${{ job.status }}  💣💥"
