name: Issue labels

on:
  issues:
    types: [labeled, closed, deleted]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_ISSUES_WEBHOOK }}

jobs:
  labelNotify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: notify label
        if: > 
          github.event.label.name == 'enhancement' 
          || github.event.label.name == 'bug' 
          || github.event.label.name == 'help wanted'
          || github.event.label.name == 'priority/high'
          || github.event.label.name == 'question'
          || github.event.label.name == 'status/waiting on upstream'
        uses: Ilshidur/action-discord@master
        with:
          args: "[${{ github.event.issue.title }} (#${{ github.event.issue.number }})](<${{ github.event.issue.html_url }}>) added `${{ github.event.label.name }}` label"
      - name: notify closed
        if: > 
          github.event.milestone == 'closed' 
        uses: Ilshidur/action-discord@master
        with:
          args: "[${{ github.event.issue.title }} (#${{ github.event.issue.number }})](<${{ github.event.issue.html_url }}>) has been `CLOSED`"
      - name: notify deleted
        if: > 
          github.event.milestone == 'deleted' 
        uses: Ilshidur/action-discord@master
        with:
          args: "[${{ github.event.issue.title }} (#${{ github.event.issue.number }})](<${{ github.event.issue.html_url }}>) has been `REMOVED`"
