name: PullRequest

on:
  pull_request:
    branches: [master]
    types: [assigned, opened, synchronize, labeled]
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

# Using env variables for step conditions to pass if vars are not found in github secrets.
env:
  ORG: ${{ secrets.IMAGE_ORG }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_TO_TEST: ${{ secrets.IMAGE_ORG }}/minecraft-server:test-${{ github.repository_owner }}-${{ github.run_id }}
  GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  pullrequest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      run-build:
        uses: octo-org/${{ secrets.IMAGE_ORG }}/minecraft-server/.github/workflows/build.yml
      run-test:
        uses: octo-org/${{ secrets.IMAGE_ORG }}/minecraft-server/.github/workflows/test.yml
      run-deploy:
        uses: octo-org/${{ secrets.IMAGE_ORG }}/minecraft-server/.github/workflows/deploy.yml
