name: Test

on:
  workflow_call:
    inputs:
      IMAGE_TO_TEST:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Run Setup Only Tests
        run: |
          tests/setuponlytests/test.sh

      - name: Run Full Minecraft Service Tests
        run: |
          tests/fulltests/test.sh
